serveral bug fixes and improvmpents
moritzgloeckl/overleaf-sync pull request #13
Opened 2020-09-10 02:19 UTC by zq1997

FIX: filter trashed project out
FIX&improvment: correct project name and enable it to be specified by
user
improvment: chdir first to get rid of annoying os.path.join and local name diretory problem (when sync local/path/filename to filename, we need to remove the local/path prefix, but with chdir, no such problem because its just filename)

2020-09-10 07:17 UTC, moritzgloeckl commented
Very nice, thank you I'm gonna take a look later today!

2020-09-12 18:17 UTC, moritzgloeckl requested changes
Sorry it took a while. How does the project name work now? Is it still possible to omit the parameter or is it necessary? I would at least add the current directory as default, as to not change current behaviour. Thanks for your work!

2020-09-12 18:17 UTC, moritzgloeckl commented on olsync/olclient.py
> +    # FIXED: use this method to filter project, not archived and not trashed
I'd remove this comment since I rather look at the git history to check what has been done

2020-09-12 18:17 UTC, moritzgloeckl commented on olsync/olclient.py
> +    def filter_projects(json_content, more_attrs=None):
Name should probably be prefixed with `_` to mark as private

2020-09-12 18:17 UTC, moritzgloeckl commented on olsync/olsync.py
> +        # and this implemention is more elegant without so many os.path.join
Would remove "FIXED" comments and add a simple comment stating why directory changes here

2020-09-13 05:20 UTC, zq1997 commented
Current implemention is **designed** always sync remote project name as the name of local directory name, lacks of flexibilities.

This PR distinguish these two names, `-p` for local directory to sync, `-n` for remote overleaf project name, if `-n` is not given, use `-p` value as its defaults.
It's a desing improvement.

And more, old implemention has some bugs, it sync to the wrong project with wrong files (you can try it with `-p` option to specify another diretory). Hence, I `chdir` at the begining, omit a lots of code and simplify its implention, also fix the bugs

2020-12-13 15:33 UTC, moritzgloeckl commented
Closed in favor of PR #19

2020-12-13 15:33 UTC, closed without merging